/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VistaOpcionLavado extends javax.swing.JFrame {
    
    public static String auxFuncio, auxRanFecha;
    public static int auxPrecio;

    /**
     * Creates new form VistaOpcionLavado
     */
    public VistaOpcionLavado() {
        initComponents();
        jLBasico.setVisible(false);
        jLCombo1.setVisible(false);
        jLCombo2.setVisible(false);
        jLCombo3.setVisible(false);
        jLDAvanzada.setVisible(false);
        jLDBasica.setVisible(false);
        jLEspecial.setVisible(false);
        jCheckCombo1.setVisible(false);
        jCheckCombo2.setVisible(false);
        jCheckCombo3.setVisible(false);
        jCheckCombo1.isSelected();
        jCheckCombo2.isSelected();
        jCheckCombo3.isSelected();
        jCheckCombos.isSelected();
        jCheckDAvanzada.isSelected();
        jCheckDBasica.isSelected();
        jCheckLBasico.isSelected();
        jCheckLEspecial.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckLBasico = new javax.swing.JCheckBox();
        jCheckLEspecial = new javax.swing.JCheckBox();
        jCheckDBasica = new javax.swing.JCheckBox();
        jCheckDAvanzada = new javax.swing.JCheckBox();
        jCheckCombos = new javax.swing.JCheckBox();
        jLBasico = new javax.swing.JLabel();
        jLEspecial = new javax.swing.JLabel();
        jLDBasica = new javax.swing.JLabel();
        jLDAvanzada = new javax.swing.JLabel();
        jCheckCombo1 = new javax.swing.JCheckBox();
        jCheckCombo2 = new javax.swing.JCheckBox();
        jCheckCombo3 = new javax.swing.JCheckBox();
        jLCombo1 = new javax.swing.JLabel();
        jLCombo2 = new javax.swing.JLabel();
        jLCombo3 = new javax.swing.JLabel();
        jBTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)), "OpcionLavado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N

        jCheckLBasico.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCheckLBasico.setText("Lavado Basico");
        jCheckLBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckLBasicoActionPerformed(evt);
            }
        });

        jCheckLEspecial.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCheckLEspecial.setText("Lavado Especial");
        jCheckLEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckLEspecialActionPerformed(evt);
            }
        });

        jCheckDBasica.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCheckDBasica.setText("Desinfeccion Basica");
        jCheckDBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDBasicaActionPerformed(evt);
            }
        });

        jCheckDAvanzada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCheckDAvanzada.setText("Desinfeccion Avanzada");
        jCheckDAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDAvanzadaActionPerformed(evt);
            }
        });

        jCheckCombos.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCheckCombos.setText("Combos");
        jCheckCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCombosActionPerformed(evt);
            }
        });

        jLBasico.setText("Depende del tipo de auto existe una tarifa. Incluye lavado exterior, lavado interior y aspirada.");

        jLEspecial.setText("Incluye lavado básico más polichado con maquina y las mejores ceras de calidad.");

        jLDBasica.setText("Con maquina generadora de ozono.");

        jLDAvanzada.setText("Además de la desinfección básica, limpieza interior con máquina de vapor.");

        jCheckCombo1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCheckCombo1.setText("Combo 1");
        jCheckCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCombo1ActionPerformed(evt);
            }
        });

        jCheckCombo2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCheckCombo2.setText("Combo 2");
        jCheckCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCombo2ActionPerformed(evt);
            }
        });

        jCheckCombo3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jCheckCombo3.setText("Combo 3");
        jCheckCombo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCombo3ActionPerformed(evt);
            }
        });

        jLCombo1.setText("Lavado, polichado y desengrasante por debajo.");

        jLCombo2.setText("Combo 1 + grafitado de chasis.");

        jLCombo3.setText("Combo 2 + tapicería (desmontado de sillas para un aseo más profundo).");

        jBTerminar.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jBTerminar.setText("Terminar");
        jBTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLBasico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckLEspecial)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDBasica)
                            .addComponent(jCheckDBasica)
                            .addComponent(jLEspecial)
                            .addComponent(jCheckLBasico))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckDAvanzada)
                            .addComponent(jLDAvanzada)
                            .addComponent(jCheckCombos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addComponent(jBTerminar)
                        .addGap(66, 66, 66))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckCombo3)
                    .addComponent(jLCombo1)
                    .addComponent(jCheckCombo1)
                    .addComponent(jLCombo3)
                    .addComponent(jLCombo2)
                    .addComponent(jCheckCombo2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jCheckLBasico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBasico)
                .addGap(18, 18, 18)
                .addComponent(jCheckLEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLEspecial)
                .addGap(18, 18, 18)
                .addComponent(jCheckDBasica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLDBasica)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBTerminar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckDAvanzada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLDAvanzada)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckCombos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jCheckCombo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCombo1)
                .addGap(16, 16, 16)
                .addComponent(jCheckCombo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCombo2)
                .addGap(18, 18, 18)
                .addComponent(jCheckCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCombo3)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTerminarActionPerformed
  
        VistaProduccion mostrar = new VistaProduccion();
        mostrar.setVisible(true);
        this.setVisible(false);               
    }//GEN-LAST:event_jBTerminarActionPerformed

    private void jCheckLBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckLBasicoActionPerformed
        
        if(jCheckLBasico.isSelected()){
        jLBasico.setVisible(rootPaneCheckingEnabled);
        jLCombo1.setVisible(false);
        jLCombo2.setVisible(false);
        jLCombo3.setVisible(false);
        jLDAvanzada.setVisible(false);
        jLDBasica.setVisible(false);
        jLEspecial.setVisible(false);
        
        jCheckCombo1.setSelected(false);
        jCheckCombo2.setSelected(false);
        jCheckCombo3.setSelected(false);
        jCheckCombos.setSelected(false);
        jCheckDAvanzada.setSelected(false);
        jCheckDBasica.setSelected(false);
        jCheckLEspecial.setSelected(false);
        
        jCheckCombo1.setVisible(false);
        jCheckCombo2.setVisible(false);
        jCheckCombo3.setVisible(false);
        }
        else{
            jLBasico.setVisible(false);
        }
    }//GEN-LAST:event_jCheckLBasicoActionPerformed

    private void jCheckLEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckLEspecialActionPerformed
        if(jCheckLEspecial.isSelected()){
        jLBasico.setVisible(false);
        jLCombo1.setVisible(false);
        jLCombo2.setVisible(false);
        jLCombo3.setVisible(false);
        jLDAvanzada.setVisible(false);
        jLDBasica.setVisible(false);
        jLEspecial.setVisible(rootPaneCheckingEnabled);
        
        jCheckCombo1.setSelected(false);
        jCheckCombo2.setSelected(false);
        jCheckCombo3.setSelected(false);
        jCheckCombos.setSelected(false);
        jCheckDAvanzada.setSelected(false);
        jCheckDBasica.setSelected(false);
        jCheckLBasico.setSelected(false);
        
        jCheckCombo1.setVisible(false);
        jCheckCombo2.setVisible(false);
        jCheckCombo3.setVisible(false);
        }
        else{
            jLEspecial.setVisible(false);
        }
    }//GEN-LAST:event_jCheckLEspecialActionPerformed

    private void jCheckDBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDBasicaActionPerformed
        if(jCheckDBasica.isSelected()){
        jLBasico.setVisible(false);
        jLCombo1.setVisible(false);
        jLCombo2.setVisible(false);
        jLCombo3.setVisible(false);
        jLDAvanzada.setVisible(false);
        jLDBasica.setVisible(rootPaneCheckingEnabled);
        jLEspecial.setVisible(false);
        
        jCheckCombo1.setSelected(false);
        jCheckCombo2.setSelected(false);
        jCheckCombo3.setSelected(false);
        jCheckCombos.setSelected(false);
        jCheckDAvanzada.setSelected(false);
        jCheckLEspecial.setSelected(false);
        jCheckLBasico.setSelected(false);
        
        jCheckCombo1.setVisible(false);
        jCheckCombo2.setVisible(false);
        jCheckCombo3.setVisible(false);
        }
        else{
            jLDBasica.setVisible(false);
        }
    }//GEN-LAST:event_jCheckDBasicaActionPerformed

    private void jCheckDAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDAvanzadaActionPerformed
        if(jCheckDAvanzada.isSelected()){
        jLBasico.setVisible(false);
        jLCombo1.setVisible(false);
        jLCombo2.setVisible(false);
        jLCombo3.setVisible(false);
        jLDAvanzada.setVisible(rootPaneCheckingEnabled);
        jLDBasica.setVisible(false);
        jLEspecial.setVisible(false);
        
        jCheckCombo1.setSelected(false);
        jCheckCombo2.setSelected(false);
        jCheckCombo3.setSelected(false);
        jCheckCombos.setSelected(false);
        jCheckDBasica.setSelected(false);
        jCheckLBasico.setSelected(false);
        jCheckLEspecial.setSelected(false);
        
        jCheckCombo1.setVisible(false);
        jCheckCombo2.setVisible(false);
        jCheckCombo3.setVisible(false);
        }
        else{
            jLDAvanzada.setVisible(false);
        }
    }//GEN-LAST:event_jCheckDAvanzadaActionPerformed

    private void jCheckCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCombosActionPerformed
        
        if(jCheckCombos.isSelected()){
            
        jCheckCombo1.setVisible(true);
        jCheckCombo2.setVisible(true);
        jCheckCombo3.setVisible(true);
        
        jLBasico.setVisible(false);
        jLCombo1.setVisible(false);
        jLCombo2.setVisible(false);
        jLCombo3.setVisible(false);
        jLDAvanzada.setVisible(false);
        jLDBasica.setVisible(false);
        jLEspecial.setVisible(false);
        
        jCheckCombo1.setSelected(false);
        jCheckCombo2.setSelected(false);
        jCheckCombo3.setSelected(false);
        jCheckDAvanzada.setSelected(false);
        jCheckDBasica.setSelected(false);
        jCheckDAvanzada.setSelected(false);
        jCheckLBasico.setSelected(false);
        jCheckLEspecial.setSelected(false);
        }
        else{
            jCheckCombo1.setVisible(false);
            jCheckCombo2.setVisible(false);
            jCheckCombo3.setVisible(false);
        }
    }//GEN-LAST:event_jCheckCombosActionPerformed

    private void jCheckCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCombo1ActionPerformed
        if(jCheckCombo1.isSelected()){
        jLBasico.setVisible(false);
        jLCombo1.setVisible(rootPaneCheckingEnabled);
        jLCombo2.setVisible(false);
        jLCombo3.setVisible(false);
        jLDAvanzada.setVisible(false);
        jLDBasica.setVisible(false);
        jLEspecial.setVisible(false);
        
        jCheckCombo2.setSelected(false);
        jCheckCombo3.setSelected(false);
        jCheckDBasica.setSelected(false);  
        jCheckLBasico.setSelected(false);
        }
        else{
            jLCombo1.setVisible(false);
        }
    }//GEN-LAST:event_jCheckCombo1ActionPerformed

    private void jCheckCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCombo2ActionPerformed
        if(jCheckCombo2.isSelected()){
        jLBasico.setVisible(false);
        jLCombo2.setVisible(rootPaneCheckingEnabled);
        jLCombo1.setVisible(false);
        jLCombo3.setVisible(false);
        jLDAvanzada.setVisible(false);
        jLDBasica.setVisible(false);
        jLEspecial.setVisible(false);
        
        jCheckCombo1.setSelected(false);
        jCheckCombo3.setSelected(false);
        jCheckDBasica.setSelected(false);
        jCheckLBasico.setSelected(false);        
        }
        else{
            jLCombo2.setVisible(false);
        }
    }//GEN-LAST:event_jCheckCombo2ActionPerformed

    private void jCheckCombo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCombo3ActionPerformed
        if(jCheckCombo3.isSelected()){
        jLBasico.setVisible(false);
        jLCombo3.setVisible(rootPaneCheckingEnabled);
        jLCombo2.setVisible(false);
        jLCombo1.setVisible(false);
        jLDAvanzada.setVisible(false);
        jLDBasica.setVisible(false);
        jLEspecial.setVisible(false);
        
        jCheckCombo2.setSelected(false);
        jCheckCombo1.setSelected(false);
        jCheckDBasica.setSelected(false); 
        jCheckLBasico.setSelected(false);
        }
        else{
            jLCombo3.setVisible(false);
        }
    }//GEN-LAST:event_jCheckCombo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionLavado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionLavado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionLavado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionLavado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaOpcionLavado().setVisible(true);
            }
        });
    }
    public static javax.swing.JButton jBTerminar;
    public static javax.swing.JCheckBox jCheckCombo1;
    public static javax.swing.JCheckBox jCheckCombo2;
    public static javax.swing.JCheckBox jCheckCombo3;
    public static javax.swing.JCheckBox jCheckCombos;
    public static javax.swing.JCheckBox jCheckDAvanzada;
    public static javax.swing.JCheckBox jCheckDBasica;
    public static javax.swing.JCheckBox jCheckLBasico;
    public static javax.swing.JCheckBox jCheckLEspecial;
    private static javax.swing.JLabel jLBasico;
    private static javax.swing.JLabel jLCombo1;
    private static javax.swing.JLabel jLCombo2;
    private static javax.swing.JLabel jLCombo3;
    private static javax.swing.JLabel jLDAvanzada;
    private static javax.swing.JLabel jLDBasica;
    private static javax.swing.JLabel jLEspecial;
    private static javax.swing.JPanel jPanel1;

/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTerminar;
    public javax.swing.JCheckBox jCheckCombo1;
    public javax.swing.JCheckBox jCheckCombo2;
    public javax.swing.JCheckBox jCheckCombo3;
    public javax.swing.JCheckBox jCheckCombos;
    public javax.swing.JCheckBox jCheckDAvanzada;
    public javax.swing.JCheckBox jCheckDBasica;
    public javax.swing.JCheckBox jCheckLBasico;
    public javax.swing.JCheckBox jCheckLEspecial;
    private javax.swing.JLabel jLBasico;
    private javax.swing.JLabel jLCombo1;
    private javax.swing.JLabel jLCombo2;
    private javax.swing.JLabel jLCombo3;
    private javax.swing.JLabel jLDAvanzada;
    private javax.swing.JLabel jLDBasica;
    private javax.swing.JLabel jLEspecial;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
*/}
